on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: yarn install
      run: yarn install
    - name: tsc
      run: tsc
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: |
          /home/runner/work/HomeworkCLI/HomeworkCLI/build/
          /home/runner/work/HomeworkCLI/HomeworkCLI/yarn.lock
